clusterDomain: cluster.local

rabbitmq:
  replicas: 3
  namespace: rabbitmq
  domainname: pi.talos.rocks
  image:
    repository: rabbitmq
    # Overrides the image tag whose default is the chart version.
    tag: "3"
    pullPolicy: Always
  restartPolicy: Always

  securityContext:
    fsGroup: 999

  containerSecurityContext:
    runAsUser: 999
    runAsNonRoot: true

  podLabels: {}
  podAnnotations: {}
  selectorLabels: {
    disktype: ssd
  }

  auth:
    tls:
      enabled: true
      failIfNoPeerCert: true
      sslOptionsVerify: verify_peer

  resources:
    requests:
      memory: "512Mi"
      cpu: "1000m"
    limits:
      memory: "1024Mi"
      cpu: "1500m"

  ## Extra annotations to be added to statefulset
  deploymenttAnnotations: {}

  pv:
    storage:
      capacity: 2Gi
      className: rook-ceph-block

  service:
    annotations: {}
    labels: {}
    issuerRef:
      name: vault-issuer
      kind: ClusterIssuer
