apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer-ext
spec:
  vault:
    path: pki_ext/sign/pi-talos-rocks
    server: https://vault.vault.svc.cluster.local:8200
    caBundle: CA_BUNDLE
    auth:
      tokenSecretRef:
        name: cert-manager-vault-token-ext
        key: token
