{{- $service := .Values.zipkin.service -}}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ include "zipkin.fullname" . }}-pod-cert
spec:
  secretName: {{ include "zipkin.fullname" . }}-pod-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  issuerRef:
    name: {{ $service.issuerRef.name }}
    kind: {{ $service.issuerRef.kind }}
  usages:
    - server auth
    - client auth
  dnsNames:
    - {{ include "zipkin.fullname" . }}
    - {{ include "zipkin.fullname" . }}.{{ .Values.zipkin.namespace }}
    - {{ include "zipkin.fullname" . }}.{{ .Values.zipkin.namespace }}.svc
    - {{ include "zipkin.fullname" . }}.{{ .Values.zipkin.namespace }}.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
