apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zipkin.fullname" . }}
  labels:
    {{- include "zipkin.commonLabels" . | nindent 4 }}
type: Opaque
data:
  oauth2-proxy.cfg: {{.Values.zipkin.proxy.config}}
