---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: rabbitmq-pod-cert
spec:
  secretName: rabbitmq-pod-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
  usages:
    - server auth
    - client auth
  commonName: "*.cluster1.rabbitmq.svc.cluster.local"
  dnsNames:
    - rabbitmq-0
    - rabbitmq-1
    - rabbitmq-2
    - rabbitmq-0.cluster1.rabbitmq
    - rabbitmq-1.cluster1.rabbitmq
    - rabbitmq-2.cluster1.rabbitmq
    - rabbitmq-0.cluster1.rabbitmq.svc
    - rabbitmq-1.cluster1.rabbitmq.svc
    - rabbitmq-2.cluster1.rabbitmq.svc
    - rabbitmq-0.cluster1.rabbitmq.svc.cluster.local
    - rabbitmq-1.cluster1.rabbitmq.svc.cluster.local
    - rabbitmq-2.cluster1.rabbitmq.svc.cluster.local
    - cluster1.rabbitmq.svc.cluster.local
