apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fileuploadservice.fullname" . }}
  labels:
    {{- include "fileuploadservice.commonLabels" . | nindent 4 }}
type: Opaque
data:
  awsAccessKeyId: {{ .Values.fileuploadservice.aws.accessKey | b64enc }}
  awsSecretAccessKey: {{ .Values.fileuploadservice.aws.secretKey | b64enc }}
