clusterDomain: cluster.local

## Optionally override the fully qualified name
# fullnameOverride: fileuploadservice

## Optionally override the name
# nameOverride: fileuploadservice

fileuploadservice:
  replicas: 1
  namespace: default
  image:
    repository: digitalpatterns/file-upload-service
    # Overrides the image tag whose default is the chart version.
    tag: latest
    pullPolicy: Always

  port: 8181
  logLevel: debug
  url: xxx

  nginx:
    image:
      repository: quay.io/ukhomeofficedigital/nginx-proxy
      tag: latest

  aws:
    region: eu-west-2
    bucketname: zzz
    accessKey: zzz
    secretKey: zzz

  keycloak:
    uri: zzz
    clientId: zzz
    realm: zzz

  restartPolicy: Always

  securityContext:
    fsGroup: 1000

  containerSecurityContext:
    runAsUser: 1000
    runAsNonRoot: true

  podLabels: {}
  podAnnotations: {}

  resources:
    requests:
      memory: "307Mi"
      cpu: "300m"
    limits:
      memory: "1536Mi"
      cpu: "1500m"


  ## Extra annotations to be added to statefulset
  deploymenttAnnotations: {}


  service:
    annotations: {}
    labels: {}
    port: 8181
    protocol: TCP
    targetPort: 8181
    issuerRef:
      name: vault-issuer
      kind: ClusterIssuer
    issuerRefExt:
      name: vault-issuer-ext
      kind: ClusterIssuer

  ingress:
    name: fileuploadservice.pi.talos.rocks
    class: nginx
