clusterDomain: cluster.local

keycloak:
  replicas: 1
  namespace: keycloak
  domainname: pi.talos.rocks
  image:
    repository: docker.io/jboss/keycloak
    # Overrides the image tag whose default is the chart version.
    tag: "11.0.2"
    pullPolicy: Always
  restartPolicy: Always

  securityContext:
    fsGroup: 1000

  containerSecurityContext:
    runAsUser: 1000
    runAsNonRoot: true

  podLabels: {}
  podAnnotations: {}
  selectorLabels: {
    disktype: ssd
  }

  db:
    name: keycloak
    port: 5432
    hostname: postgresql.databases.svc.cluster.local

  resources:
    requests:
      memory: "256Mi"
      cpu: "500m"
    limits:
      memory: "512Mi"
      cpu: "1000m"

  ## Extra annotations to be added to statefulset
  deploymenttAnnotations: {}

  service:
    annotations: {}
    labels: {}
    port: 8080
    protocol: TCP
    targetPort: 8080
    issuerRef:
      name: vault-issuer
      kind: ClusterIssuer
    issuerRefExt:
      name: vault-issuer-ext
      kind: ClusterIssuer

  ingress:
    name: keycloak.pi.talos.rocks
    class: traefik
