zipkin:
  replicas: 1

  image:
    repository: openzipkin/zipkin-aws
    # Overrides the image tag whose default is the chart version.
    tag: ""
    pullPolicy: Always
  restartPolicy: Always

  securityContext:
    fsGroup: 1000

  containerSecurityContext:
    runAsUser: 1000
    runAsNonRoot: true

  podLabels: {}
  podAnnotations: {}

  resources:
    requests:
      memory: "256Mi"
      cpu: "400m"
    limits:
      memory: "512Mi"
      cpu: "8000m"


  ## Extra annotations to be added to statefulset
  deploymenttAnnotations: {}

  service:
    annotations: {}
    labels: {}
    port: 8080
    protocol: TCP
    targetPort: 8080
    issuerRef:
      name: vault-issuer
      kind: ClusterIssuer
    issuerRefExt:
      name: vault-issuer-ext
      kind: ClusterIssuer

  ingress:
    name: zipkin.pi.talos.rocks
    class: nginx

  proxy:
    image:
      repository: quay.io/oauth2-proxy/oauth2-proxy
      tag: v5.1.1
    config: xxx
