apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "referencedataservice.fullname" . }}
  {{- if .Values.referencedataservice.deploymenttAnnotations }}
  annotations:
    {{- with .Values.referencedataservice.deploymenttAnnotations }}
      {{- range $key, $value := . }}
      {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
      {{- end }}
      {{- end }}
  {{- end }}
  labels:
    {{- include "referencedataservice.commonLabels" . | nindent 4 }}
    service: {{ include "referencedataservice.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "referencedataservice.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.referencedataservice.replicas }}
  revisionHistoryLimit: 3
  minReadySeconds: 5
  strategy:
    # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: {{ include "referencedataservice.fullname" . }}
        service: {{ include "referencedataservice.fullname" . }}
        {{- include "referencedataservice.selectorLabels" . | nindent 8 }}
          {{- with .Values.referencedataservice.podLabels }}
          {{- toYaml . | nindent 8 }}
          {{- end }}
      annotations:
        {{- with .Values.referencedataservice.podAnnotations }}
        {{- range $key, $value := . }}
        {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 8 }}
        {{- end }}
        {{- end }}
    spec:
      restartPolicy: {{ .Values.referencedataservice.restartPolicy }}
      securityContext:
        {{- toYaml .Values.referencedataservice.securityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.referencedataservice.image.repository }}:{{ .Values.referencedataservice.image.tag }}"
        imagePullPolicy: {{ .Values.referencedataservice.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.referencedataservice.containerSecurityContext | nindent 12 }}
        command: ["/bin/sh"]
        args: ["-c", "/app/run.sh -Djava.security.egd=file:/dev/./urandom -Djavax.net.ssl.keyStore=/etc/keystore/keystore.p12 -Djavax.net.ssl.keyStorePassword=changeit -Djavax.net.ssl.trustStore=/etc/keystore/cacerts -Djavax.net.ssl.trustStoreType=pkcs12 -Djavax.net.ssl.trustStorePassword=changeit -jar /app/reference-data-service.jar"]
        {{- with .Values.referencedataservice.lifecycleHooks }}
        lifecycle:
          {{- tpl . $ | nindent 12 }}
        {{- end }}
        env:
          - name: VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                name: referencedataservice
                key: token
          - name: SPRING_PROFILES_ACTIVE
            value: {{ .Values.referencedataservice.springProfileActive | quote }}
          - name: AWS_SECRETS_MANAGER_ENABLED
            value: "false"
        ports:
          - name: https
            containerPort: {{ .Values.referencedataservice.service.targetPort }}
            protocol: TCP
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /actuator/info
            port: {{ .Values.referencedataservice.service.targetPort }}
          initialDelaySeconds: 120
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /actuator/health
            port: {{ .Values.referencedataservice.service.targetPort }}
          initialDelaySeconds: 30
          timeoutSeconds: 1
        resources:
          {{- toYaml .Values.referencedataservice.resources | nindent 12 }}
        volumeMounts:
          - name: certs
            mountPath: /certs
            readOnly: true
      volumes:
        - name: certs
          secret:
            secretName: {{ include "referencedataservice.fullname" . }}-pod-cert
      imagePullSecrets:
        - name: regcred
