clusterDomain: cluster.local
## Optionally override the fully qualified name
# fullnameOverride: cubejsbackend
# nameOverride: cubejsbackend

cubejsbackend:
  replicas: 1
  image:
    repository: digitalpatterns/talos-cubejs-backend
    # Overrides the image tag whose default is the chart version.
    tag: ""
    pullPolicy: Always
  configservice:
    url: https://configservice.vault.svc.cluster.local
    token: xxx
  profile: dev

  restartPolicy: Always

  securityContext:
    fsGroup: 1000

  containerSecurityContext:
    runAsUser: 1000
    runAsNonRoot: true

  podLabels: {}
  podAnnotations: {}

  resources:
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 0.5
      memory: 400Mi

  ## Extra annotations to be added to statefulset
  deploymenttAnnotations: {}

  service:
    annotations: {}
    labels: {}
    port: 4001
    protocol: TCP
    targetPort: 4001
    issuerRef:
      name: vault-issuer
      kind: ClusterIssuer
    issuerRefExt:
      name: vault-issuer-ext
      kind: ClusterIssuer

  ingress:
    name: cubejsbackend.pi.talos.rocks
    class: nginx
