---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-pod-cert
spec:
  secretName: vault-pod-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
  usages:
    - server auth
    - client auth
  commonName: "*.vault.svc.cluster.local"
  dnsNames:
    - vault.vault
    - vault-0.vault
    - vault-1.vault
    - vault-2.vault
    - vault.vault.svc
    - vault-0.vault.svc
    - vault-1.vault.svc
    - vault-2.vault.svc
    - vault.vault.svc.cluster.local
    - vault-0.vault.svc.cluster.local
    - vault-1.vault.svc.cluster.local
    - vault-2.vault.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
