apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Values.redis.namespace }}
  name: {{ include "redis.fullname" . }}
  {{- if .Values.redis.deploymenttAnnotations }}
  annotations:
    {{- with .Values.redis.deploymenttAnnotations }}
      {{- range $key, $value := . }}
      {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
      {{- end }}
      {{- end }}
  {{- end }}
  labels:
    {{- include "redis.commonLabels" . | nindent 4 }}
    service: {{ include "redis.fullname" . }}
spec:
  serviceName: redis
  replicas: {{ .Values.redis.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "redis.selectorLabels" . | nindent 6 }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "redis.fullname" . }}
      spec:
        storageClassName: {{ .Values.redis.pv.storage.className }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.redis.pv.storage.capacity }}
  template:
    metadata:
      labels:
        name: {{ include "redis.fullname" . }}
        service: {{ include "redis.fullname" . }}
        {{- include "redis.selectorLabels" . | nindent 8 }}
        {{- with .Values.redis.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.redis.podAnnotations }}
          {{- range $key, $value := . }}
          {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 8 }}
          {{- end }}
          {{- end }}
    spec:
      restartPolicy: {{ .Values.redis.restartPolicy }}
      securityContext:
        {{- toYaml .Values.redis.securityContext | nindent 8 }}
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.redis.containerSecurityContext | nindent 12 }}
        {{- with .Values.redis.lifecycleHooks }}
        lifecycle:
          {{- tpl . $ | nindent 12 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.redis.service.targetPort }}
          protocol: {{ .Values.redis.service.protocol }}
        resources:
          {{- toYaml .Values.redis.resources | nindent 12 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: {{ include "redis.fullname" . }}
