apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "refdata.fullname" . }}
  labels:
    {{- include "refdata.commonLabels" . | nindent 4 }}
#  annotations:
#    "helm.sh/hook": pre-install,pre-upgrade,pre-rollback
#    "helm.sh/hook-delete-policy": before-hook-creation
#    "helm.sh/hook-weight": "3"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.refdata.image.repository }}:{{ .Values.refdata.image.tag }}"
          imagePullPolicy: {{ .Values.refdata.image.pullPolicy }}
          env:
            - name: DB_HOSTNAME
              value: {{ .Values.refdata.db.hostname }}
            - name: DB_PORT
              value: "{{ .Values.refdata.db.port }}"
            - name: DB_NAME
              value: {{ .Values.refdata.db.name }}
            - name: DB_DEFAULT_NAME
              value: {{ .Values.refdata.db.default.name }}
            - name: DB_OPTIONS
              value: {{ .Values.refdata.db.options }}
            - name: DB_JDBC_OPTIONS
              value: {{ .Values.refdata.db.jdbcOptions }}
            - name: FLYWAY_USER
              value: {{ .Values.refdata.db.default.user }}
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "refdata.fullname" . }}
                  key: defaultPassword
            - name: DB_OWNERNAME
              value: {{ .Values.refdata.db.owner.user }}
            - name: DB_OWNERPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "refdata.fullname" . }}
                  key: ownerPassword
            - name: DB_SCHEMA
              value: {{ .Values.refdata.db.schema }}
            - name: FLYWAY_PLACEHOLDERS_AUTHENTICATORUSER
              value: {{ .Values.refdata.db.authenticator.user }}
            - name: FLYWAY_PLACEHOLDERS_AUTHENTICATORPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "refdata.fullname" . }}
                  key: authenticatorPassword
            - name: FLYWAY_PLACEHOLDERS_ANONUSER
              value: {{ .Values.refdata.db.anon.user }}
            - name: FLYWAY_PLACEHOLDERS_SERVICEUSER
              value: {{ .Values.refdata.db.service.user }}
            - name: FLYWAY_PLACEHOLDERS_READONLYUSER
              value: {{ .Values.refdata.db.readonly.user }}
