apiVersion: v1
kind: Secret
metadata:
  name: {{ include "refdata.fullname" . }}
  labels:
    {{- include "refdata.commonLabels" . | nindent 4 }}
type: Opaque
data:
  defaultPassword: {{.Values.refdata.db.defaultPassword | b64enc}}
  ownerPassword: {{.Values.refdata.db.ownerPassword | b64enc}}
  authenticatorPassword: {{.Values.refdata.db.authenticatorPassword | b64enc}}
