clusterDomain: cluster.local

mongodb:
  replicas: 3
  namespace: databases
  domainname: pi.talos.rocks
  image:
    repository: mongo
    # Overrides the image tag whose default is the chart version.
    tag: "4"
    pullPolicy: Always
  restartPolicy: Always

  securityContext:
    fsGroup: 999

  containerSecurityContext:
    runAsUser: 999
    runAsNonRoot: true

  podLabels: {}
  podAnnotations: {}
  selectorLabels: {
    disktype: ssd
  }

  resources:
    requests:
      memory: "64Mi"
      cpu: "10m"
    limits:
      memory: "256Mi"
      cpu: "500m"

  ## Extra annotations to be added to statefulset
  deploymenttAnnotations: {}

  pv:
    storage:
      capacity: 10Gi
      className: rook-ceph-block

  service:
    annotations: {}
    labels: {}
    port: 27017
    protocol: TCP
    targetPort: 27017
    issuerRef:
      name: vault-issuer
      kind: ClusterIssuer
