apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ .Values.keycloak.ingress.class }}
  namespace: {{ .Values.keycloak.namespace }}
  name: {{ include "keycloak.fullname" . }}
spec:
  rules:
    - host: {{ .Values.keycloak.ingress.name }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "keycloak.fullname" . }}
                port:
                  number: {{ .Values.keycloak.service.port }}
  # This section is only required if TLS is to be enabled for the Ingress
  tls:
    - hosts:
        - {{ .Values.keycloak.ingress.name }}
      secretName: {{ include "keycloak.fullname" . }}-ext-cert
