{{- $service := .Values.mongodb.service -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}
  {{- with $service.annotations }}
  annotations:
    {{- range $key, $value := . }}
      {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
      {{- end }}
      {{- end }}
  labels:
    {{- include "mongodb.commonLabels" . | nindent 4 }}
      {{- with $service.labels }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
  namespace: {{ .Values.mongodb.namespace }}
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - port: {{ $service.port }}
      targetPort: {{ $service.targetPort }}
      protocol: {{ $service.protocol }}
  selector:
    {{- include "mongodb.selectorLabels" . | nindent 4 }}
