clusterDomain: cluster.local
referencedataservice:
  replicas: 1

  image:
    repository: digitalpatterns/talos-reference-data-service
    tag: latest
    pullPolicy: Always
  fullname: talos
  domainname: pi.talos.rocks
#  configservice:
#    url: https://configservice.default.svc.cluster.local
#    token: xxx
#  aws:
#    access_key: test
#    secret_key: test
  springProfileActive: dev
  restartPolicy: Always

  securityContext:
    fsGroup: 1000

  containerSecurityContext:
    runAsUser: 1000
    runAsNonRoot: true

  podLabels: {}
  podAnnotations: {}

  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  deploymenttAnnotations: {}

  service:
    annotations: {}
    labels: {}
    port: 443
    protocol: TCP
    targetPort: 8443
    issuerRef:
      name: vault-issuer
      kind: ClusterIssuer
    issuerRefExt:
      name: vault-issuer-ext
      kind: ClusterIssuer

  ingress:
    name: postgrest.pi.talos.rocks
    class: traefik
