apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgrest.fullname" . }}
  labels:
    {{- include "postgrest.commonLabels" . | nindent 4 }}
type: Opaque
data:
  dbUri: {{.Values.postgrest.db.uri | b64enc}}
  jwtSecret: {{.Values.postgrest.db.jwtSecret}}
