---
  {{- $service := .Values.presto.service -}}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ include "presto.fullname" . }}-pod-cert
spec:
  secretName: {{ include "presto.fullname" . }}-pod-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  issuerRef:
    name: {{ $service.issuerRef.name }}
    kind: {{ $service.issuerRef.kind }}
  usages:
    - server auth
    - client auth
  commonName: "*.presto.{{ .Values.presto.namespace }}.svc.cluster.local"
  dnsNames:
    - presto-0
    - presto-coordinator-0
    - presto-1
    - presto-2
    - presto-coordinator-0.presto-coordinator.{{ .Values.presto.namespace }}
    - presto-0.presto.{{ .Values.presto.namespace }}
    - presto-1.presto.{{ .Values.presto.namespace }}
    - presto-2.presto.{{ .Values.presto.namespace }}
    - presto-0.presto.{{ .Values.presto.namespace }}.svc
    - presto-coordinator-0.presto-coordinator.{{ .Values.presto.namespace }}.svc
    - presto-1.presto.{{ .Values.presto.namespace }}.svc
    - presto-2.presto.{{ .Values.presto.namespace }}.svc
    - presto-0.presto.{{ .Values.presto.namespace }}.svc.cluster.local
    - presto-coordinator-0.presto-coordinator.{{ .Values.presto.namespace }}.svc.cluster.local
    - presto-1.presto.{{ .Values.presto.namespace }}.svc.cluster.local
    - presto-2.presto.{{ .Values.presto.namespace }}.svc.cluster.local
    - {{ include "presto.fullname" . }}-coordinator.{{ .Values.presto.namespace }}.svc.cluster.local
    - {{ include "presto.fullname" . }}.{{ .Values.presto.namespace }}.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
