apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "presto.fullname" . }}-coordinator
  labels:
    {{- include "presto.commonLabels" . | nindent 4 }}
    service: {{ include "presto.fullname" . }}
data:
  node.properties: |
    node.environment={{ .Values.presto.node.environment }}
    node.data-dir={{ .Values.presto.node.dataDir }}
    plugin.dir={{ .Values.presto.node.pluginDir }}
  jvm.config: |
    -server
    -Xmx{{ .Values.presto.jvm.maxHeapSize }}
    -XX:+{{ .Values.presto.jvm.gcMethod.type }}
    -XX:G1HeapRegionSize={{ .Values.presto.jvm.gcMethod.g1.heapRegionSize }}
    -XX:+UseGCOverheadLimit
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+HeapDumpOnOutOfMemoryError
    -XX:+ExitOnOutOfMemoryError
    -Djdk.attach.allowAttachSelf=true
    -Djavax.net.ssl.trustStore=/etc/keystore/cacerts
    -Djavax.net.ssl.trustStoreType=pkcs12
    -Djavax.net.ssl.trustStorePassword=changeit
  config.properties: |
    coordinator=true
  {{- if gt .Values.presto.workers 0.5 }}
    node-scheduler.include-coordinator=false
  {{- else }}
    node-scheduler.include-coordinator=true
  {{- end }}
    http-server.http.port={{ .Values.presto.config.http.port }}
    query.max-memory={{ .Values.presto.config.query.maxMemory }}
    query.max-memory-per-node={{ .Values.presto.config.query.maxMemoryPerNode }}
    discovery-server.enabled=true
    discovery.uri=https://{{ include "presto.fullname" . }}-coordinator-0.{{ include "presto.fullname" . }}-coordinator.{{ .Values.presto.namespace }}.svc.cluster.local:{{ .Values.presto.config.https.port }}
    http-server.http.enabled=true
    node.internal-address-source=FQDN
    http-server.https.enabled=true
    http-server.https.port={{ .Values.presto.config.https.port }}
    http-server.https.keystore.path=/etc/keystore/keystore.p12
    http-server.https.keystore.key=changeit
    http-server.https.truststore.path=/etc/keystore/cacerts
    http-server.https.truststore.key=changeit
    internal-communication.https.required=false
    internal-communication.https.keystore.path=/etc/keystore/keystore.p12
    internal-communication.https.keystore.key=changeit
    internal-communication.https.truststore.path=/etc/keystore/cacerts
    internal-communication.https.truststore.key=changeit
    workerInfo.http-client.trust-store-path=/etc/keystore/cacerts
    workerInfo.http-client.trust-store-password=changeit
    dynamic.http-client.trust-store-path=/etc/keystore/cacerts
    dynamic.http-client.trust-store-password=changeit
    discovery.http-client.trust-store-path=/etc/keystore/cacerts
    discovery.http-client.trust-store-password=changeit
  log.properties: |
    io.prestosql={{ .Values.presto.log.presto.level }}
