apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "presto.fullname" . }}-catalog
  labels:
    {{- include "presto.commonLabels" . | nindent 4 }}
    service: {{ include "presto.fullname" . }}
data:
  mongodb.properties: |
    connector.name=mongodb
    mongodb.seeds=mongodb-0.mongodb.default.svc.cluster.local,mongodb-1.mongodb.default.svc.cluster.local,mongodb-2.mongodb.default.svc.cluster.local
    mongodb.credentials=camundaAdmin:FSPaFZ47HtXAyYZQmbtK3m2fnrndh7PU@admin
    mongodb.ssl.enabled=false
    mongodb.required-replica-set=rs0
    mongodb.schema-collection=presto_schema
#  atlas.properties: |
#    connector.name=mongodb
#    mongodb.seeds=dev-shard-00-00.he4yv.mongodb.net:27017,dev-shard-00-01.he4yv.mongodb.net:27017,dev-shard-00-02.he4yv.mongodb.net:27017
#    mongodb.credentials=presto:aNfpKwzHRtqWVLX9WyYnTybr8mN3VU@admin
#    mongodb.ssl.enabled=true
#    mongodb.required-replica-set=atlas-12j6h4-shard-0
#    mongodb.schema-collection=presto_schema
  jmx.properties: |
    connector.name=jmx
  memory.properties: |
    connector.name=memory
  tpcds.properties: |
    connector.name=tpcds
    tpcds.splits-per-node=4
  tpch.properties: |
    connector.name=tpch
    tpch.splits-per-node=4
