{{- $service := .Values.presto.service -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "presto.fullname" . }}-coordinator
  {{- with $service.annotations }}
  annotations:
    {{- range $key, $value := . }}
      {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
      {{- end }}
      {{- end }}
  labels:
    {{- include "presto.commonLabels" . | nindent 4 }}
      {{- with $service.labels }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
  namespace: {{ .Values.presto.namespace }}
spec:
  sessionAffinity: None
  ports:
    - port: {{ $service.targetPort }}
      targetPort: {{ $service.targetPort }}
  clusterIP: None
  selector:
    {{- include "presto.selectorLabels" . | nindent 4 }}
