apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Values.presto.namespace }}
  name: {{ include "presto.fullname" . }}-coordinator
  {{- if .Values.presto.deploymenttAnnotations }}
  annotations:
    {{- with .Values.presto.deploymenttAnnotations }}
      {{- range $key, $value := . }}
      {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
      {{- end }}
      {{- end }}
  {{- end }}
  labels:
    {{- include "presto.commonLabels" . | nindent 4 }}
    service: {{ include "presto.fullname" . }}
spec:
  replicas: {{ .Values.presto.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "presto.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "presto.fullname" . }}-coordinator
  volumeClaimTemplates:
    - metadata:
        name: {{ include "presto.fullname" . }}-coordinator-pvc
      spec:
        storageClassName: {{ .Values.presto.pv.storage.className }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.presto.pv.storage.capacity }}
  template:
    metadata:
      labels:
        name: {{ include "presto.fullname" . }}
        service: {{ include "presto.fullname" . }}
        {{- include "presto.selectorLabels" . | nindent 8 }}
        {{- with .Values.presto.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.presto.podAnnotations }}
          {{- range $key, $value := . }}
          {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 8 }}
          {{- end }}
          {{- end }}
    spec:
      restartPolicy: {{ .Values.presto.restartPolicy }}
      securityContext:
        {{- toYaml .Values.presto.securityContext | nindent 8 }}
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - name: {{ include "presto.fullname" . }}-coordinator
          configMap:
            name: {{ include "presto.fullname" . }}-coordinator
        - name: {{ include "presto.fullname" . }}-catalog
          configMap:
            name: {{ include "presto.fullname" . }}-catalog
        - name: certs
          secret:
            secretName: {{ include "presto.fullname" . }}-pod-cert
        - name: cacerts
          secret:
            secretName: ca
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.presto.image.repository }}:{{ .Values.presto.image.tag }}"
          imagePullPolicy: {{ .Values.presto.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.presto.containerSecurityContext | nindent 12 }}
          {{- with .Values.presto.lifecycleHooks }}
          lifecycle:
            {{- tpl . $ | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ include "presto.fullname" . }}-coordinator
              mountPath: "{{ .Values.presto.config.path }}"
            - name: {{ include "presto.fullname" . }}-coordinator-pvc
              mountPath: "{{ .Values.presto.node.dataDir }}"
            - name: {{ include "presto.fullname" . }}-catalog
              mountPath: "{{ .Values.presto.config.path }}/catalog/"
            - name: certs
              mountPath: /certs
              readOnly: true
            - name: cacerts
              mountPath: /cacerts
              readOnly: true
          ports:
            - name: http
              containerPort: 8443
              protocol: TCP
          resources:
            {{- toYaml .Values.presto.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      nodeSelector:
        beta.kubernetes.io/arch: amd64
