clusterDomain: cluster.local
#fullnameOverride: talos
## Optionally override the name
# nameOverride: eforms

talosui:
  replicas: 1

  image:
    repository: digitalpatterns/talos-ui
    # Overrides the image tag whose default is the chart version.
    tag: "latest"
    pullPolicy: Always
  fullname: talos
  domainname: pi.talos.rocks
  namespace: default
  configservice:
    url: https://configservice.vault.svc.cluster.local
  springProfileActive: dev
  secretsManagerEnabled: false

  restartPolicy: Always

  securityContext:
    fsGroup: 1000

  containerSecurityContext:
    runAsUser: 1000
    runAsNonRoot: true

  podLabels: {}
  podAnnotations: {}

  resources:
    requests:
      memory: "256Mi"
      cpu: "400m"
    limits:
      memory: "512Mi"
      cpu: "800m"


  ## Extra annotations to be added to statefulset
  deploymenttAnnotations: {}

  service:
    annotations: {}
    labels: {}
    port: 443
    protocol: TCP
    targetPort: 8443
    issuerRef:
      name: vault-issuer
      kind: ClusterIssuer
    issuerRefExt:
      name: vault-issuer-ext
      kind: ClusterIssuer

  ingress:
    name: www.pi.talos.rocks
    class: nginx
