clusterDomain: cluster.local
talosengine:
  replicas: 1
  image:
    repository: digitalpatterns/talos-engine
    tag: "latest"
    pullPolicy: Always
  domainname: pi.talos.rocks
  namespace: default
  configservice:
    url: https://configservice.vault.svc.cluster.local
  secretsManagerEnabled: false
  springProfileActive: dev
  restartPolicy: Always
  securityContext:
    fsGroup: 1000
  containerSecurityContext:
    runAsUser: 1000
    runAsNonRoot: true

  podLabels: {}
  podAnnotations: {}

  resources:
    requests:
      memory: "512Mi"
      cpu: "400m"
    limits:
      memory: "1024Mi"
      cpu: "1000m"

  deploymenttAnnotations: {}

  service:
    annotations: {}
    labels: {}
    port: 443
    protocol: TCP
    targetPort: 8443
    issuerRef:
      name: vault-issuer
      kind: ClusterIssuer
    issuerRefExt:
      name: vault-issuer-ext
      kind: ClusterIssuer

  ingress:
    name: engine.pi.talos.rocks
    class: traefik
