---
  {{- $service := .Values.formbuilder.service -}}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ include "formbuilder.fullname" . }}-ext-cert
spec:
  secretName: {{ include "formbuilder.fullname" . }}-ext-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  issuerRef:
    name: {{ $service.issuerRefExt.name }}
    kind: {{ $service.issuerRefExt.kind }}
  usages:
    - server auth
    - client auth
  commonName: "{{ .Values.formbuilder.ingress.name }}"
  dnsNames:
    - {{ .Values.formbuilder.ingress.name }}
  ipAddresses:
    - 127.0.0.1
