apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "formbuilder.fullname" . }}
  {{- if .Values.formbuilder.deploymenttAnnotations }}
  annotations:
    {{- with .Values.formbuilder.deploymenttAnnotations }}
      {{- range $key, $value := . }}
      {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
      {{- end }}
      {{- end }}
  {{- end }}
  labels:
    {{- include "formbuilder.commonLabels" . | nindent 4 }}
    service: {{ include "formbuilder.fullname" . }}
spec:
  selector:
    matchLabels:
      {{- include "formbuilder.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.formbuilder.replicas }}
  revisionHistoryLimit: 3
  minReadySeconds: 5
  strategy:
    # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: {{ include "formbuilder.fullname" . }}
        service: {{ include "formbuilder.fullname" . }}
        {{- include "formbuilder.selectorLabels" . | nindent 8 }}
          {{- with .Values.formbuilder.podLabels }}
          {{- toYaml . | nindent 8 }}
          {{- end }}
      annotations:
        {{- with .Values.formbuilder.podAnnotations }}
        {{- range $key, $value := . }}
        {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 8 }}
        {{- end }}
        {{- end }}
    spec:
      restartPolicy: {{ .Values.formbuilder.restartPolicy }}
      securityContext:
        {{- toYaml .Values.formbuilder.securityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.formbuilder.image.repository }}:{{ .Values.formbuilder.image.tag }}"
        imagePullPolicy: {{ .Values.formbuilder.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.formbuilder.containerSecurityContext | nindent 12 }}
        {{- with .Values.formbuilder.lifecycleHooks }}
        lifecycle:
          {{- tpl . $ | nindent 12 }}
        {{- end }}
        env:
          - name: NODE_EXTRA_CA_CERTS
            value: /ca/ca.crt
          - name: FORMBUILDER_PORT
            value: "{{ .Values.formbuilder.service.targetPort }}"
        ports:
          - name: http
            containerPort: {{ .Values.formbuilder.service.targetPort }}
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.formbuilder.service.targetPort }}
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: {{ .Values.formbuilder.service.targetPort }}
          initialDelaySeconds: 30
          timeoutSeconds: 1
        resources:
          {{- toYaml .Values.formbuilder.resources | nindent 12 }}
        volumeMounts:
          - mountPath: /config
            name: config-volume
          - name: ca
            mountPath: /ca
            readOnly: true
      volumes:
        - name: ca
          secret:
            secretName: ca
        - name: config-volume
          secret:
            defaultMode: 420
            secretName: formbuilder
