clusterDomain: cluster.local

redis:
  replicas: 1
  namespace: databases
  domainname: pi.talos.rocks
  image:
    repository: redis
    # Overrides the image tag whose default is the chart version.
    tag: "6"
    pullPolicy: Always
  restartPolicy: Always

  securityContext:
    fsGroup: 999

  containerSecurityContext:
    runAsUser: 999
    runAsNonRoot: true

  podLabels: {}
  podAnnotations: {}
  selectorLabels: {
    disktype: ssd
  }

  resources:
    requests:
      memory: "64Mi"
      cpu: "10m"
    limits:
      memory: "256Mi"
      cpu: "500m"

  ## Extra annotations to be added to statefulset
  deploymenttAnnotations: {}

  pv:
    storage:
      capacity: 1Gi
      className: longhorn

  service:
    annotations: {}
    labels: {}
    port: 6379
    protocol: TCP
    targetPort: 6379
