apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  name: {{ include "postgresql.fullname" . }}
  namespace: {{ .Values.postgresql.namespace }}
spec:
  storageClassName: {{ .Values.postgresql.pv.storage.className }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.pv.storage.capacity }}

