apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    {{- include "postgresql.commonLabels" . | nindent 4 }}
  namespace: {{ .Values.postgresql.namespace }}
type: Opaque
data:
  password: {{ .Values.postgresql.db.password | b64enc }}
