{{- $service := .Values.postgresql.service -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}
  {{- with $service.annotations }}
  annotations:
    {{- range $key, $value := . }}
      {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
      {{- end }}
      {{- end }}
  labels:
    {{- include "postgresql.commonLabels" . | nindent 4 }}
      {{- with $service.labels }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
  namespace: {{ .Values.postgresql.namespace }}
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - port: {{ $service.port }}
      targetPort: {{ $service.targetPort }}
      protocol: {{ $service.protocol }}
  selector:
    {{- include "postgresql.selectorLabels" . | nindent 4 }}
