---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  namespace: {{ .Values.rabbitmq.namespace }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  namespace: {{ .Values.rabbitmq.namespace }}
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  namespace: {{ .Values.rabbitmq.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "rabbitmq.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "rabbitmq.fullname" . }}
