{{- $service := .Values.rabbitmq.service -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}-client
  {{- with $service.annotations }}
  annotations:
    {{- range $key, $value := . }}
      {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
      {{- end }}
      {{- end }}
  labels:
    {{- include "rabbitmq.commonLabels" . | nindent 4 }}
      {{- with $service.labels }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
  namespace: {{ .Values.rabbitmq.namespace }}
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: managements
      port: 15671
      targetPort: 15671
      protocol: TCP
    - name: management
      port: 15672
      targetPort: 15672
      protocol: TCP
    - name: prometheuss
      port: 15691
      targetPort: 15691
      protocol: TCP
    - name: prometheus
      port: 15692
      targetPort: 15692
      protocol: TCP
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP
    - name: amqps
      port: 5671
      targetPort: 5671
      protocol: TCP
    - name: mqtt
      port: 1883
      targetPort: 1883
      protocol: TCP
    - name: mqtts
      port: 8883
      targetPort: 8883
      protocol: TCP
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}-headless
  namespace: {{ .Values.rabbitmq.namespace }}
spec:
  clusterIP: None
  ports:
    - name: epmd
      port: 4369
      targetPort: 4369
      protocol: TCP
    - name: cluster-rpc
      port: 25672
      targetPort: 25672
      protocol: TCP
    - name: cluster-rpcs
      port: 25671
      targetPort: 25671
      protocol: TCP
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  sessionAffinity: None
