apiVersion: v1
kind: Secret
metadata:
  name: {{ include "refdataprecog.fullname" . }}
  labels:
    {{- include "refdataprecog.commonLabels" . | nindent 4 }}
type: Opaque
data:
  defaultPassword: {{.Values.refdataprecog.db.defaultPassword | b64enc}}
  ownerPassword: {{.Values.refdataprecog.db.ownerPassword | b64enc}}
  authenticatorPassword: {{.Values.refdataprecog.db.authenticatorPassword | b64enc}}
  iotPassword: {{.Values.refdataprecog.db.iotPassword | b64enc}}
